#Análise de Pacientes com Coronavírus 🦠

### Etapa 01: Importação do Conjunto de Dados

In [118]:
# Importação de bibliotecas
import pandas as pd
import numpy as np

In [119]:
# Importando o conjunto de dados dos pacientes
url = '/content/covid_data.csv'
dados = pd.read_csv(url)

In [120]:
# Verificando se a leitura foi feita com sucesso
dados.head()

USMER  MEDICAL_UNIT  SEX  PATIENT_TYPE   DATE_DIED  INTUBED  PNEUMONIA  \
0      2             1    1             1  03/05/2020       97          1   
1      2             1    2             1  03/06/2020       97          1   
2      2             1    2             2  09/06/2020        1          2   
3      2             1    1             1  12/06/2020       97          2   
4      2             1    2             1  21/06/2020       97          2   

   AGE  PREGNANT  DIABETES  ...  ASTHMA  INMSUPR  HIPERTENSION  OTHER_DISEASE  \
0   65         2         2  ...       2        2             1              2   
1   72        97         2  ...       2        2             1              2   
2   55        97         1  ...       2        2             2              2   
3   53         2         2  ...       2        2             2              2   
4   68        97         1  ...       2        2             1              2   

   CARDIOVASCULAR  OBESITY  RENAL_CHRONIC  TOBACCO  CLASIFFICATION_FINAL  ICU  
0               2        2              2        2                     3   97  
1               2        1              1        2                     5   97  
2               2        2              2        2                     3    2  
3               2        2              2        2                     7   97  
4               2        2              2        2                     3   97  

[5 rows x 21 columns]

###Etapa 02: Exploração do Conjunto de Dados

In [121]:
# Obtendo as informações gerais do dataframe
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column                Non-Null Count    Dtype 
---  ------                --------------    ----- 
 0   USMER                 1048575 non-null  int64 
 1   MEDICAL_UNIT          1048575 non-null  int64 
 2   SEX                   1048575 non-null  int64 
 3   PATIENT_TYPE          1048575 non-null  int64 
 4   DATE_DIED             1048575 non-null  object
 5   INTUBED               1048575 non-null  int64 
 6   PNEUMONIA             1048575 non-null  int64 
 7   AGE                   1048575 non-null  int64 
 8   PREGNANT              1048575 non-null  int64 
 9   DIABETES              1048575 non-null  int64 
 10  COPD                  1048575 non-null  int64 
 11  ASTHMA                1048575 non-null  int64 
 12  INMSUPR               1048575 non-null  int64 
 13  HIPERTENSION          1048575 non-null  int64 
 14  OTHER_DISEASE         1048575 non-null  int64 
 15

In [122]:
# Descobrindo a quantidade de valores nulos (NaN)
dados.isnull().sum()

USMER                   0
MEDICAL_UNIT            0
SEX                     0
PATIENT_TYPE            0
DATE_DIED               0
INTUBED                 0
PNEUMONIA               0
AGE                     0
PREGNANT                0
DIABETES                0
COPD                    0
ASTHMA                  0
INMSUPR                 0
HIPERTENSION            0
OTHER_DISEASE           0
CARDIOVASCULAR          0
OBESITY                 0
RENAL_CHRONIC           0
TOBACCO                 0
CLASIFFICATION_FINAL    0
ICU                     0
dtype: int64

In [123]:
# Verificando os valores da única coluna do tipo 'object'
dados['DATE_DIED'].unique()

array(['03/05/2020', '03/06/2020', '09/06/2020', '12/06/2020',
       '21/06/2020', '9999-99-99', '26/02/2020', '05/04/2020',
       '08/05/2020', '20/05/2020', '17/07/2020', '13/01/2020',
       '22/01/2020', '29/01/2020', '13/02/2020', '18/02/2020',
       '19/02/2020', '20/02/2020', '24/02/2020', '04/03/2020',
       '07/03/2020', '12/03/2020', '14/03/2020', '18/03/2020',
       '27/03/2020', '28/03/2020', '29/03/2020', '02/04/2020',
       '06/04/2020', '07/04/2020', '08/04/2020', '09/04/2020',
       '10/04/2020', '11/04/2020', '12/04/2020', '13/04/2020',
       '14/04/2020', '15/04/2020', '16/04/2020', '17/04/2020',
       '18/04/2020', '20/04/2020', '21/04/2020', '22/04/2020',
       '23/04/2020', '24/04/2020', '25/04/2020', '26/04/2020',
       '27/04/2020', '28/04/2020', '29/04/2020', '30/04/2020',
       '01/05/2020', '02/05/2020', '04/05/2020', '05/05/2020',
       '06/05/2020', '07/05/2020', '09/05/2020', '10/05/2020',
       '11/05/2020', '12/05/2020', '13/05/2020', '14/05

###Etapa 03: Manipulação do Conjunto de Dados

In [124]:
# Substituindo os valores de 97 e 99 por valores nulos (NaN)
valores_trocar = [97, 98, 99]
dados.replace(valores_trocar, np.nan, inplace=True)

In [125]:
# Verificando a alteração
dados['INTUBED']

0          NaN
1          NaN
2          1.0
3          NaN
4          NaN
          ... 
1048570    NaN
1048571    2.0
1048572    NaN
1048573    NaN
1048574    NaN
Name: INTUBED, Length: 1048575, dtype: float64

In [126]:
# Obtendo os valores da coluna de gravidez
dados['PREGNANT'].unique()

array([ 2., nan,  1.])

In [127]:
# Substituindo os valores nulos (NaN) da coluna de gravidez por dois
dados['PREGNANT'].replace(np.nan, 2, inplace=True)
dados['PREGNANT'].unique()

<ipython-input-127-44b7f8094421>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dados['PREGNANT'].replace(np.nan, 2, inplace=True)


array([2., 1.])

In [128]:
# Removendo os registros com valores nulos (NaN)
dados.dropna(inplace=True)

In [129]:
# Obtendo os valores da coluna de gênero
dados['SEX'].unique()

array([2, 1])

In [130]:
# Trocando os valores da coluna de gênero para melhor legibilidade
dados['SEX'] = dados['SEX'].apply(lambda x: 'Female' if x == 1 else 'Man')
dados['SEX'].unique()

array(['Man', 'Female'], dtype=object)

In [131]:
# Removendo a coluna de estado do paciente
dados.drop(columns=['PATIENT_TYPE'], inplace=True)
dados.head()
# Motivo: a coluna possui um único valor

USMER  MEDICAL_UNIT     SEX   DATE_DIED  INTUBED  PNEUMONIA   AGE  \
2       2             1     Man  09/06/2020      1.0        2.0  55.0   
5       2             1  Female  9999-99-99      2.0        1.0  40.0   
8       2             1  Female  9999-99-99      2.0        2.0  37.0   
9       2             1  Female  9999-99-99      2.0        2.0  25.0   
11      2             1     Man  9999-99-99      2.0        2.0  24.0   

    PREGNANT  DIABETES  COPD  ASTHMA  INMSUPR  HIPERTENSION  OTHER_DISEASE  \
2        2.0       1.0   2.0     2.0      2.0           2.0            2.0   
5        2.0       2.0   2.0     2.0      2.0           2.0            2.0   
8        2.0       1.0   2.0     2.0      2.0           1.0            2.0   
9        2.0       2.0   2.0     2.0      2.0           2.0            2.0   
11       2.0       2.0   2.0     2.0      2.0           2.0            2.0   

    CARDIOVASCULAR  OBESITY  RENAL_CHRONIC  TOBACCO  CLASIFFICATION_FINAL  ICU  
2              2.0      2.0            2.0      2.0                     3  2.0  
5              2.0      2.0            2.0      2.0                     3  2.0  
8              2.0      1.0            2.0      2.0                     3  2.0  
9              2.0      2.0            2.0      2.0                     3  2.0  
11             2.0      2.0            2.0      2.0                     3  2.0

In [132]:
# Obtendo os valores únicos da coluna de classificação
dados['CLASIFFICATION_FINAL'].unique()

array([3, 7, 6, 5, 1, 2, 4])

In [133]:
# Obtendo os registros (índices) com valores acima de três (inconclusivos)
filtro = dados['CLASIFFICATION_FINAL'] > 3
registros = dados[filtro].sort_values('CLASIFFICATION_FINAL', ascending=True).index
registros

Index([ 660017,  660309,  660303,  660288,  660282,  660269,  660268,  660265,
        660261,  660254,
       ...
        304298,  304299,  304303,  304315,  304322,  304323,  304329,  304337,
        304231, 1048571],
      dtype='int64', length=81214)

In [134]:
# Removendo os registros sem conclusão
dados.drop(registros, inplace=True)
dados.head()

USMER  MEDICAL_UNIT     SEX   DATE_DIED  INTUBED  PNEUMONIA   AGE  \
2       2             1     Man  09/06/2020      1.0        2.0  55.0   
5       2             1  Female  9999-99-99      2.0        1.0  40.0   
8       2             1  Female  9999-99-99      2.0        2.0  37.0   
9       2             1  Female  9999-99-99      2.0        2.0  25.0   
11      2             1     Man  9999-99-99      2.0        2.0  24.0   

    PREGNANT  DIABETES  COPD  ASTHMA  INMSUPR  HIPERTENSION  OTHER_DISEASE  \
2        2.0       1.0   2.0     2.0      2.0           2.0            2.0   
5        2.0       2.0   2.0     2.0      2.0           2.0            2.0   
8        2.0       1.0   2.0     2.0      2.0           1.0            2.0   
9        2.0       2.0   2.0     2.0      2.0           2.0            2.0   
11       2.0       2.0   2.0     2.0      2.0           2.0            2.0   

    CARDIOVASCULAR  OBESITY  RENAL_CHRONIC  TOBACCO  CLASIFFICATION_FINAL  ICU  
2              2.0      2.0            2.0      2.0                     3  2.0  
5              2.0      2.0            2.0      2.0                     3  2.0  
8              2.0      1.0            2.0      2.0                     3  2.0  
9              2.0      2.0            2.0      2.0                     3  2.0  
11             2.0      2.0            2.0      2.0                     3  2.0

In [135]:
# Verificando se o processo foi feito com sucesso
dados.sort_values('CLASIFFICATION_FINAL', ascending=True)

USMER  MEDICAL_UNIT     SEX   DATE_DIED  INTUBED  PNEUMONIA   AGE  \
341768       2             6     Man  01/05/2020      1.0        1.0  50.0   
472094       2            12  Female  9999-99-99      2.0        1.0  72.0   
472100       1            12     Man  9999-99-99      2.0        1.0  48.0   
472106       2            12     Man  9999-99-99      2.0        1.0  58.0   
472107       2            12     Man  9999-99-99      2.0        1.0  31.0   
...        ...           ...     ...         ...      ...        ...   ...   
94146        2             4     Man  9999-99-99      2.0        1.0  60.0   
94127        1             4  Female  9999-99-99      2.0        2.0  44.0   
94124        1             4  Female  9999-99-99      2.0        2.0  77.0   
94527        2             4  Female  9999-99-99      2.0        1.0  55.0   
1047933      1            13  Female  9999-99-99      2.0        2.0  77.0   

         PREGNANT  DIABETES  COPD  ASTHMA  INMSUPR  HIPERTENSION  \
341768        2.0       1.0   2.0     2.0      2.0           1.0   
472094        2.0       2.0   2.0     2.0      2.0           1.0   
472100        2.0       1.0   2.0     2.0      2.0           2.0   
472106        2.0       2.0   2.0     2.0      2.0           2.0   
472107        2.0       1.0   2.0     2.0      2.0           2.0   
...           ...       ...   ...     ...      ...           ...   
94146         2.0       2.0   2.0     2.0      2.0           2.0   
94127         2.0       2.0   2.0     2.0      2.0           2.0   
94124         2.0       1.0   2.0     2.0      2.0           2.0   
94527         2.0       2.0   2.0     2.0      2.0           2.0   
1047933       2.0       1.0   2.0     2.0      1.0           1.0   

         OTHER_DISEASE  CARDIOVASCULAR  OBESITY  RENAL_CHRONIC  TOBACCO  \
341768             2.0             2.0      2.0            2.0      2.0   
472094             2.0             2.0      2.0            2.0      2.0   
472100             2.0             2.0      1.0            2.0      2.0   
472106             2.0             2.0      2.0            2.0      1.0   
472107             2.0             2.0      1.0            2.0      1.0   
...                ...             ...      ...            ...      ...   
94146              2.0             2.0      2.0            2.0      2.0   
94127              2.0             2.0      2.0            2.0      2.0   
94124              2.0             2.0      2.0            2.0      2.0   
94527              2.0             2.0      1.0            2.0      2.0   
1047933            2.0             2.0      2.0            2.0      2.0   

         CLASIFFICATION_FINAL  ICU  
341768                      1  2.0  
472094                      1  2.0  
472100                      1  2.0  
472106                      1  2.0  
472107                      1  2.0  
...                       ...  ...  
94146                       3  2.0  
94127                       3  2.0  
94124                       3  2.0  
94527                       3  2.0  
1047933                     3  2.0  

[108203 rows x 20 columns]

In [136]:
# Alterando os valores da coluna de data da morte
dados['DATE_DIED'] = dados['DATE_DIED'].replace('9999-99-99', 'Not died')
dados.head()

USMER  MEDICAL_UNIT     SEX   DATE_DIED  INTUBED  PNEUMONIA   AGE  \
2       2             1     Man  09/06/2020      1.0        2.0  55.0   
5       2             1  Female    Not died      2.0        1.0  40.0   
8       2             1  Female    Not died      2.0        2.0  37.0   
9       2             1  Female    Not died      2.0        2.0  25.0   
11      2             1     Man    Not died      2.0        2.0  24.0   

    PREGNANT  DIABETES  COPD  ASTHMA  INMSUPR  HIPERTENSION  OTHER_DISEASE  \
2        2.0       1.0   2.0     2.0      2.0           2.0            2.0   
5        2.0       2.0   2.0     2.0      2.0           2.0            2.0   
8        2.0       1.0   2.0     2.0      2.0           1.0            2.0   
9        2.0       2.0   2.0     2.0      2.0           2.0            2.0   
11       2.0       2.0   2.0     2.0      2.0           2.0            2.0   

    CARDIOVASCULAR  OBESITY  RENAL_CHRONIC  TOBACCO  CLASIFFICATION_FINAL  ICU  
2              2.0      2.0            2.0      2.0                     3  2.0  
5              2.0      2.0            2.0      2.0                     3  2.0  
8              2.0      1.0            2.0      2.0                     3  2.0  
9              2.0      2.0            2.0      2.0                     3  2.0  
11             2.0      2.0            2.0      2.0                     3  2.0

In [137]:
# Filtrando as colunas que possuem os valores de um e dois apenas
valores_booleanos = [1, 2]
colunas_booleanas = dados.columns[dados.apply(lambda coluna: coluna.isin(valores_booleanos).all())]
colunas_booleanas

Index(['USMER', 'INTUBED', 'PNEUMONIA', 'PREGNANT', 'DIABETES', 'COPD',
       'ASTHMA', 'INMSUPR', 'HIPERTENSION', 'OTHER_DISEASE', 'CARDIOVASCULAR',
       'OBESITY', 'RENAL_CHRONIC', 'TOBACCO', 'ICU'],
      dtype='object')

In [138]:
# Trocando os valores de um e dois para True e False
for coluna in colunas_booleanas:
  dados[coluna] = dados[coluna].apply(lambda num: True if num == 1 else False)

In [139]:
# Verificando se o processo foi bem executado
dados.head()

USMER  MEDICAL_UNIT     SEX   DATE_DIED  INTUBED  PNEUMONIA   AGE  \
2   False             1     Man  09/06/2020     True      False  55.0   
5   False             1  Female    Not died    False       True  40.0   
8   False             1  Female    Not died    False      False  37.0   
9   False             1  Female    Not died    False      False  25.0   
11  False             1     Man    Not died    False      False  24.0   

    PREGNANT  DIABETES   COPD  ASTHMA  INMSUPR  HIPERTENSION  OTHER_DISEASE  \
2      False      True  False   False    False         False          False   
5      False     False  False   False    False         False          False   
8      False      True  False   False    False          True          False   
9      False     False  False   False    False         False          False   
11     False     False  False   False    False         False          False   

    CARDIOVASCULAR  OBESITY  RENAL_CHRONIC  TOBACCO  CLASIFFICATION_FINAL  \
2            False    False          False    False                     3   
5            False    False          False    False                     3   
8            False     True          False    False                     3   
9            False    False          False    False                     3   
11           False    False          False    False                     3   

      ICU  
2   False  
5   False  
8   False  
9   False  
11  False

###Etapa 04: Análises do Conjunto de Dados

#####Análise 01: Quantidade Pacientes por Gênero

In [142]:
# Descobrindo a quantidade de pacientes por gênero
dados['SEX'].value_counts()

SEX
Man       66796
Female    41407
Name: count, dtype: int64

In [143]:
# Exibindo em porcentagem
dados['SEX'].value_counts(normalize=True)

SEX
Man       0.617321
Female    0.382679
Name: proportion, dtype: float64

#####Análise 02: Taxa de Mortalidade

In [156]:
# Descobrindo a quantidade de pacientes que morreram
nao_morreu = 'Not died'
taxa_mortalidade = dados.query('@nao_morreu != DATE_DIED')['SEX'].value_counts()
taxa_mortalidade

SEX
Man       30538
Female    16613
Name: count, dtype: int64

In [158]:
# Atribuindo os valores para variáveis
homens_morreram = taxa_mortalidade.iloc[0]
mulheres_morreram = taxa_mortalidade.iloc[1]

In [160]:
# Descobrindo a quantidade de pacientes que não morreram
nao_morreu = 'Not died'
taxa_vivos = dados.query('@nao_morreu == DATE_DIED')['SEX'].value_counts()
taxa_vivos

SEX
Man       36258
Female    24794
Name: count, dtype: int64

In [161]:
# Atribuindo os valores para variáveis
homens_nao_morreram = taxa_vivos.iloc[0]
mulheres_nao_morreram = taxa_vivos.iloc[1]

In [164]:
# Realizando o cálculo para descobrir a taxa de mortalidade (homens)
taxa_homens = homens_morreram / (homens_nao_morreram + homens_morreram) * 100
taxa_homens

45.71830648541829

In [166]:
# Realizando o cálculo para descobrir a taxa de mortalidade (mulheres)
taxa_mulheres = mulheres_morreram / (mulheres_nao_morreram + mulheres_morreram) * 100
taxa_mulheres

40.12123553988456